---
cs_env_debug: "{{ lookup('ansible.builtin.env', 'DEBUG', default=false) | bool }}"
cs_no_log: "{{ not cs_env_debug }}"

# cs_vm_ssh_service_user_id: "arpan" # Only for patching
cs_vm_ssh_service_user_id: "cloudinit" # Only for patching

ansible_user: "{{ cs_vm_ssh_service_user_id }}"

ansible_ssh_private_key_file: "/tmp/.ssh/id_rsa_home_lab"
cs_cluster_name: "blr-home"

root_ca_key_pem: "{{ lookup('home_lab_secrets', 'secret/root_ca').root_ca_key_pem }}"
root_ca_key_password: "{{ lookup('home_lab_secrets', 'secret/root_ca').root_ca_key_password }}"
root_ca_cert_pem: "{{ lookup('home_lab_secrets', 'secret/root_ca').root_ca_cert_pem }}"
