---
cs_env_debug: "{{ lookup('ansible.builtin.env', 'DEBUG', default=false) | bool }}"
cs_no_log: "{{ not cs_env_debug }}"

# cs_vm_ssh_service_user_id: "arpan" # Only for patching
cs_vm_ssh_service_user_id: "cloudinit" # Only for patching

ansible_user: "{{ cs_vm_ssh_service_user_id }}"

###############################################################################
pv_vault_info_map:
    x86_64:
        vault_arch: amd64
        sha256sum:
            1.18.3: 405ec904a45c2261e2c091640fb805bf5904fd2fe8a991ebc58d2eb64f9a269e
    aarch64:
        vault_arch: arm64
        sha256sum:
            1.18.3: 816df690b9240cf50828331012081b4221da4eecf30e1ce4d85053113138aab7
vault_rv_version: 1.18.3

pv_vault_user: vault
pv_vault_group: vault
pv_vault_cluster_name: vault-cluster
pv_vault_bin_path: /usr/local/bin/vault
pv_vault_base_path: /opt/vault
pv_vault_backup_base_path: /var/backups/vault
pv_vault_autopilot_update_interval_seconds: 5
pv_vault_autopilot_reconcile_interval_seconds: "{{ pv_vault_autopilot_update_interval_seconds + 5 }}"
pv_vault_systemd_service: vault
pv_vault_backup_systemd_service: vault-backup
