---
cs_minio_kes_group_name: kes
cs_minio_kes_user_name: "{{ cs_minio_kes_group_name }}"

cs_minio_kes_working_dir: "/app/minio_kes"
cs_minio_kes_config_file: "{{ cs_minio_kes_working_dir }}/config.yaml"
cs_minio_kes_container_name: minio-kes
cs_minio_kes_cert_dir: "{{ cs_minio_kes_working_dir }}/certs"
cs_minio_kes_cert_file: "{{ cs_minio_kes_cert_dir }}/cert.pem"
cs_minio_kes_cert_key_file: "{{ cs_minio_kes_cert_dir }}/cert-key.pem"
cs_minio_kes_cert_ca: "{{ cs_minio_kes_cert_dir }}/server-ca.pem"
cs_minio_kes_vault_client_cert: "{{ cs_minio_kes_cert_dir }}/vault-client-cert.pem"
cs_minio_kes_vault_client_key: "{{ cs_minio_kes_cert_dir }}/vault-client-key.pem"
cs_minio_kes_vault_ca_cert: "{{ cs_minio_kes_cert_dir }}/vault-ca-cert.pem"
cs_minio_kes_version: 2024-10-31T07-42-41Z
cs_minio_kes_port: 3000
cs_minio_kes_cluster_name: blr-home
