---
# Some host specific variables are in host_vars/rb4-m1/database/postgres.yml
cs_postgres_container_name: postgres
cs_postgres_network_name: postgres
cs_postgres_run_user: "999"
cs_postgres_run_group: "999"
cs_postgres_version: "16.5"
cs_postgres_docker_image: docker.io/library/postgres

# No touchy touchy zone
cs_postgres_dir: "/app/postgres"
cs_postgres_data_dir: "{{ cs_postgres_dir }}/data"
cs_postgres_certs_dir: "{{ cs_postgres_dir }}/certs"
cs_postgres_certs_privkey_file: "{{ cs_postgres_certs_dir }}/privkey.pem"
cs_postgres_certs_cert_file: "{{ cs_postgres_certs_dir }}/cert.pem"
cs_postgres_certs_chain_file: "{{ cs_postgres_certs_dir }}/chain.pem"
cs_postgres_hba_file: "{{ cs_postgres_dir }}/pg_hba.conf"
cs_postgres_cluster_name: blr-home
cs_postgres_docker_image_tag: "{{ cs_postgres_version }}-bookworm"
