---
collections:
    - name: community.general
      version: 10.1.0
    - name: community.crypto
      version: 2.22.3
    - name: amazon.aws
      version: 9.0.0
    - name: community.docker
      version: 4.1.0
    - name: ansible.posix
      version: 1.6.2
    - name: kewlfft.aur
      version: 0.11.1
    - name: arpanrec.nebula
      version: 1.11.4
    - name: community.hashi_vault
      version: 6.2.0
roles:
    - name: geerlingguy.docker
      version: 7.4.1
