---
collections:
    - name: community.general
      version: 10.1.0
    - name: community.crypto
      version: 2.22.3
    - name: community.docker
      version: 4.1.0
    - name: ansible.posix
      version: 1.6.2
    - name: arpanrec.nebula
      version: 1.11.4
roles:
    - name: geerlingguy.docker
      version: 7.4.1
