---
- name: Collabora | Make sure existing container is stopped
  community.general.docker_container:
      name: "{{ cs_collabora_container_name }}"
      state: absent
      force_kill: true

- name: Collabora | Create directories
  ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: "0755"
  with_items:
      - "{{ cs_collabora_dir }}"
      - "{{ cs_collabora_cert_dir }}"
      - "{{ cs_collabora_cert_pem_file | dirname }}"
      - "{{ cs_collabora_privkey_pem_file | dirname }}"
      - "{{ cs_collabora_chain_pem_file | dirname }}"
      - "{{ cs_collabora_fullchain_pem_file | dirname }}"

- name: Collabora | Create SSL Private key
  community.crypto.openssl_privatekey:
      path: "{{ cs_collabora_privkey_pem_file }}"
      size: 4096
      mode: "0600"
      owner: "{{ cs_collabora_run_user_id }}"
      group: "{{ cs_collabora_run_group_id }}"

- name: Collabora | Create SSL CSR
  community.crypto.openssl_csr:
      path: "{{ cs_collabora_cert_dir }}/csr.pem"
      privatekey_path: "{{ cs_collabora_privkey_pem_file }}"
      common_name: "{{ ansible_fqdn }}"
      subject_alt_name:
          - DNS:{{ ansible_fqdn }}
          - DNS:{{ ansible_hostname }}
          - IP:127.0.0.1
          - IP:127.0.1.1
          - DNS:localhost
      key_usage:
          - "digitalSignature"
          - "keyEncipherment"
          - "keyAgreement"
      extended_key_usage:
          - "serverAuth"
      create_subject_key_identifier: true
      mode: "0644"
      owner: "{{ cs_collabora_run_user_id }}"
      group: "{{ cs_collabora_run_group_id }}"

- name: Collabora | Sign SSL CSR
  community.crypto.x509_certificate:
      path: "{{ cs_collabora_cert_pem_file }}"
      csr_path: "{{ cs_collabora_cert_dir }}/csr.pem"
      provider: ownca
      ownca_privatekey_content: "{{ root_ca_key_pem }}"
      ownca_privatekey_passphrase: "{{ root_ca_key_passphrase }}"
      ownca_content: "{{ root_ca_cert_pem }}"
      mode: "0644"
      return_content: true
      owner: "{{ cs_collabora_run_user_id }}"
      group: "{{ cs_collabora_run_group_id }}"
  register: cs_collabora_ssl_cert

- name: Collabora | Write Full chain
  ansible.builtin.copy:
      content: |+
          {{ cs_collabora_ssl_cert.certificate | trim }}
          {{ root_ca_cert_pem }}
      dest: "{{ cs_collabora_fullchain_pem_file }}"
      mode: "0644"
      owner: "{{ cs_collabora_run_user_id }}"
      group: "{{ cs_collabora_run_group_id }}"

- name: Collabora | Write ownca CA certificate
  ansible.builtin.copy:
      content: "{{ root_ca_cert_pem }}"
      dest: "{{ cs_collabora_chain_pem_file }}"
      mode: "0644"
      remote_src: false
      owner: "{{ cs_collabora_run_user_id }}"
      group: "{{ cs_collabora_run_group_id }}"

- name: Collabora | Start docker container
  community.docker.docker_container:
      name: "{{ cs_collabora_container_name }}"
      image: "{{ cs_collabora_docker_image }}:{{ cs_collabora_docker_image_tag }}"
      state: started
      user: "{{ cs_collabora_run_user_id }}:{{ cs_collabora_run_group_id }}"
      restart_policy: unless-stopped
      privileged: true
      ports:
          - "{{ cs_collabora_https_port }}:{{ cs_collabora_https_port }}"
      volumes:
          - "{{ cs_collabora_cert_pem_file }}:/etc/coolwsd/cert.pem"
          - "{{ cs_collabora_privkey_pem_file }}:/etc/coolwsd/key.pem"
          - "{{ cs_collabora_chain_pem_file }}:/usr/local/ssl/certs/ca-chain.cert.pem"
          - "{{ cs_collabora_chain_pem_file }}:/etc/coolwsd/ca-chain.cert.pem"
      env:
          aliasgroup1: "{{ cs_nc_protocol }}://{{ ansible_fqdn }}:{{ cs_nc_port }}"
          username: "{{ cs_collabora_admin_user }}"
          password: "{{ cs_collabora_admin_password }}"
          domain: "{{ ansible_fqdn }}:{{ cs_nc_port }}"
          server_name: "{{ ansible_fqdn }}:{{ cs_nc_port }}"
          extra_params: "--port {{ cs_collabora_https_port }} --o:ssl.enable=true --o:ssl.termination=false
              --o:ssl.ssl_verification=false --o:mount_jail_tree=false --o:logging.level=warning
              --o:home_mode.enable=true --o:security.seccomp=true
              --o:remote_font_config.url={{
              cs_nc_protocol }}://{{ ansible_fqdn }}:{{
              cs_nc_port }}/apps/richdocuments/settings/fonts.json"
          DONT_GEN_SSL_CERT: "1"
          LC_CTYPE: "C.UTF-8"
          TZ: "Asia/Kolkata"
          dictionaries: "de_DE en_GB en_US es_ES fr_FR it nl pt_BR pt_PT ru"

- name: Collabora | UFW | Allow Collabora
  community.general.ufw:
      rule: allow
      port: "{{ cs_collabora_https_port }}"
      proto: tcp
      state: enabled
      comment: "Allow Collabora port, Managed by Ansible home-lab playbook."
