---
# - name: MinIO | Install | Include common crypt mount
#   ansible.builtin.include_tasks:
#       file: tasks/common/crypt_mount.yml
#   vars:
#       cs_crypt_mount_vault_id: "{{ cs_minio_external_disk_id }}"
#       cs_crypt_machine_cluster: "{{ cs_minio_minio_cluster_name }}"

- name: MinIO | Install | Gather Facts
  ansible.builtin.setup:
      gather_subset: all

- name: MinIO | Set config facts
  ansible.builtin.set_fact:
      cs_minio_minio_port: "{{ __minio_details.port }}"
      cs_minio_minio_console_port: "{{ __minio_details.console_port }}"
      cs_minio_minio_region: "{{ __minio_details.region }}"
  vars:
      __minio_details: "{{ lookup('home_lab_secrets', 'secret/' + cs_minio_minio_cluster_name + '/'
          + inventory_hostname + '/minio') }}"

- name: MinIO | Assert | Set cs_minio_minio_kes_cluster_name and cs_minio_minio_kes_cluster_node_name
  ansible.builtin.set_fact:
      cs_minio_minio_kes_cluster_name: "{{ cs_minio_minio_kes_cluster_name | d(cs_minio_minio_cluster_name)
          | mandatory }}"
      cs_minio_minio_kes_cluster_node_name: "{{ cs_minio_minio_kes_cluster_node_name | d(inventory_hostname)
          | mandatory }}"

- name: MinIO | Set __minio_server_kes_secret_dict
  ansible.builtin.set_fact:
      __minio_server_kes_secret_dict: "{{ lookup('home_lab_secrets', 'managed-secrets/minio-kes/clusters/'
          + cs_minio_kes_cluster_name + '/servers/' + cs_minio_minio_kes_cluster_node_name + '/config') }}"

- name: MinIO | Set cs_minio_minio_kes_endpoint
  ansible.builtin.set_fact:
      cs_minio_minio_kes_endpoint: "https://{{ __minio_server_kes_secret_dict.fqdn }}:\
          {{ __minio_server_kes_secret_dict.port }}"

- name: MinIO | Install | Create group
  ansible.builtin.group:
      name: "{{ cs_minio_minio_group_name }}"
      state: present
      system: true
  register: minio_server_tmp_group_creation

- name: MinIO | Install | Create User
  ansible.builtin.user:
      name: "{{ cs_minio_minio_user_name }}"
      group: "{{ cs_minio_minio_group_name }}"
      state: present
      create_home: false
      system: true
      shell: /bin/false
  register: minio_server_tmp_user_creation

- name: MinIO | Install | Download binary
  ansible.builtin.get_url:
      dest: "/usr/local/bin/minio"
      mode: "0755"
      owner: root
      group: root
      checksum: "sha256:{{ cs_minio_minio_bin_info_map[ansible_architecture]['sha256sum'][cs_minio_minio_version] }}"
      url: "https://dl.min.io/server/minio/release/linux-\
          {{ cs_minio_minio_bin_info_map[ansible_architecture]['cs_minio_minio_arch'] }}/archive/minio.\
          {{ cs_minio_minio_version }}"

- name: MinIO | Install | Create Directories
  ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      owner: "{{ cs_minio_minio_user_name }}"
      group: "{{ cs_minio_minio_group_name }}"
      mode: "0750"
  loop:
      - "{{ cs_minio_minio_certs_dir }}"
      - "{{ cs_minio_minio_certs_dir }}/CAs"
      - "{{ cs_minio_minio_data_dir }}"
      - "{{ cs_minio_minio_kes_cert_dir }}"

- name: MinIO | Install | Fix Permissions of data directory
  ansible.builtin.shell:
      cmd: |+
          chown -R {{ cs_minio_minio_user_name }}:{{ cs_minio_minio_group_name }} {{ item }};
          find {{ item }} -type d -exec chmod 0750 {} \;
          find {{ item }} -type f -exec chmod 0640 {} \;
  changed_when: true
  with_items:
      - "{{ cs_minio_minio_data_dir }}"
      - "{{ cs_minio_minio_certs_dir }}"
      - "{{ cs_minio_minio_kes_cert_dir }}"

- name: MinIO | Install | Write server private key
  community.crypto.openssl_privatekey:
      path: "{{ cs_minio_minio_private_key }}"
      type: RSA
      size: 4096
      mode: "0640"
      owner: "{{ cs_minio_minio_user_name }}"
      group: "{{ cs_minio_minio_group_name }}"

- name: MinIO | Install | Write server CSR
  community.crypto.openssl_csr:
      path: "{{ cs_minio_minio_private_key }}.csr"
      privatekey_path: "{{ cs_minio_minio_private_key }}"
      common_name: "{{ inventory_hostname }}"
      basic_constraints: CA:FALSE
      basic_constraints_critical: true
      key_usage:
          - digitalSignature
          - keyEncipherment
      extended_key_usage:
          - serverAuth
      subject_alt_name: "{{ ansible_all_ipv4_addresses | map('regex_replace', '^(.*)$', 'IP:\\1') | list
          + ['DNS:' + ansible_hostname, 'DNS:' + ansible_fqdn, 'DNS:' + inventory_hostname] }}"
      subject_alt_name_critical: true
      mode: "0640"
      owner: "{{ cs_minio_minio_user_name }}"
      group: "{{ cs_minio_minio_group_name }}"

- name: MinIO | Install | Write server Certificate
  community.crypto.x509_certificate:
      path: "{{ cs_minio_minio_cert_file }}"
      csr_path: "{{ cs_minio_minio_private_key }}.csr"
      ownca_content: "{{ root_ca_cert_pem }}"
      ownca_privatekey_content: "{{ root_ca_key_pem }}"
      ownca_privatekey_passphrase: "{{ root_ca_key_password }}"
      provider: ownca
      mode: "0640"
      owner: "{{ cs_minio_minio_user_name }}"
      group: "{{ cs_minio_minio_group_name }}"

- name: MinIO | Install | Write server certificate chain
  ansible.builtin.copy:
      content: "{{ root_ca_cert_pem }}"
      dest: "{{ cs_minio_kes_cert_ca }}"
      mode: "0640"
      owner: "{{ cs_minio_minio_user_name }}"
      group: "{{ cs_minio_minio_group_name }}"

- name: MinIO | Install | Write KES Client Admin Certificates
  ansible.builtin.copy:
      content: "{{ item.content }}"
      dest: "{{ item.dest }}"
      owner: "{{ cs_minio_minio_user_name }}"
      group: "{{ cs_minio_minio_group_name }}"
      mode: "0640"
  loop:
      - content: "{{ __minio_server_kes_secret_dict.admin_cert }}\n"
        dest: "{{ cs_minio_minio_kes_admin_cert }}"
      - content: "{{ __minio_server_kes_secret_dict.admin_key }}\n"
        dest: "{{ cs_minio_minio_kes_admin_key }}"
      - content: "{{ __minio_server_kes_secret_dict.admin_ca }}\n"
        dest: "{{ cs_minio_minio_kes_ca_cert }}"

- name: MinIO | Install | Create User and Password
  ansible.builtin.set_fact:
      minio_server_root_password: "{{ lookup('ansible.builtin.password', '/dev/null', length=40,
          chars=['ascii_letters', 'digits']) }}"
      minio_server_root_user: "{{ lookup('community.general.random_string', special=false, length=12) }}"

- name: MinIO | Install | Write the Password to Vault
  become: false
  delegate_to: localhost
  home_lab_secrets:
      key: "managed-secrets/minio/clusters/{{ cs_minio_minio_cluster_name }}/servers/{{ inventory_hostname }}/config"
      action: "write"
      value:
          root_user: "{{ minio_server_root_user }}"
          root_password: "{{ minio_server_root_password }}"
          ipv4s: "{{ ansible_all_ipv4_addresses }}"
          hostname: "{{ ansible_hostname }}"
          fqdn: "{{ ansible_fqdn }}"
          server_port: "{{ cs_minio_minio_port }}"
          console_port: "{{ cs_minio_minio_console_port }}"
          server_version: "{{ cs_minio_minio_version }}"
          kes:
              cluster_name: "{{ cs_minio_minio_kes_cluster_name }}"
              cluster_node_name: "{{ cs_minio_minio_kes_cluster_node_name }}"

- name: MinIO | Install | Create Env File
  ansible.builtin.copy:
      content: |+
          MINIO_KMS_KES_ENDPOINT={{ cs_minio_minio_kes_endpoint }}
          MINIO_KMS_KES_KEY_FILE={{ cs_minio_minio_kes_admin_key }}
          MINIO_KMS_KES_CERT_FILE={{ cs_minio_minio_kes_admin_cert }}
          MINIO_KMS_KES_CAPATH={{ cs_minio_minio_kes_ca_cert }}
          MINIO_KMS_KES_KEY_NAME=default
          MINIO_ROOT_USER={{ minio_server_root_user }}
          MINIO_ROOT_PASSWORD={{ minio_server_root_password }}
          MINIO_REGION=us-east-1
          MINIO_VOLUMES={{ cs_minio_minio_data_dir }}
          MINIO_OPTS="--address ':{{ cs_minio_minio_port }}' --console-address ':{{
            cs_minio_minio_console_port }}' --certs-dir {{ cs_minio_minio_certs_dir }}"
      dest: "{{ cs_minio_minio_env_file }}"
      owner: "{{ cs_minio_minio_user_name }}"
      group: "{{ cs_minio_minio_group_name }}"
      mode: "0640"

- name: MinIO | Install | Enable UFW
  community.general.ufw:
      rule: allow
      port: "{{ item.port }}"
      proto: tcp
      state: enabled
      comment: "Allow Minio {{ item.comment }} port, Managed by Ansible home-lab playbook."
  loop:
      - port: "{{ cs_minio_minio_port }}"
        comment: "S3"
      - port: "{{ cs_minio_minio_console_port }}"
        comment: "Console"

- name: MinIO | Install | Create Systemd Service
  ansible.builtin.template:
      src: "templates/minio/{{ cs_minio_minio_systemd_service }}.j2"
      dest: "/etc/systemd/system/{{ cs_minio_minio_systemd_service }}"
      owner: root
      group: root
      mode: "0644"

- name: MinIO | Install | Start Systemd Service
  ansible.builtin.systemd_service:
      name: "{{ cs_minio_minio_systemd_service }}"
      state: restarted
      daemon_reload: true
      daemon_reexec: true
      enabled: true
      force: true

- name: MinIO | Install | Wait for Minio to start
  ansible.builtin.uri:
      url: "https://{{ ansible_all_ipv4_addresses[0] }}:{{ cs_minio_minio_port }}/minio/health/live"
      status_code: 200
      timeout: 3
      method: GET
      validate_certs: false
  register: minio_server_health_check
  until: minio_server_health_check.status == 200
  retries: 10
  delay: 1
