---
- name: Minio | Install | Include common crypt mount
  ansible.builtin.include_tasks:
      file: tasks/common/crypt_mount.yml
  vars:
      cs_crypt_mount_vault_id: "{{ cs_minio_external_disk_id }}"
      cs_crypt_machine_cluster: "{{ cs_minio_minio_cluster_name }}"

- name: Minio | Install | Gather Facts
  ansible.builtin.setup:
      gather_subset: all

- name: Mini0 | Get Config details
  become: false
  delegate_facts: true
  delegate_to: localhost
  community.hashi_vault.vault_kv2_get:
      url: "https://{{ vault_ha_client.vault_ha_hostname }}:{{ vault_ha_client.vault_ha_port }}"
      path: "{{ cs_minio_minio_cluster_name }}/{{ inventory_hostname }}/minio"
      token: "{{ vault_ha_client.token }}"
      validate_certs: true
      engine_mount_point: "secret"
  environment:
      VAULT_CACERT: "{{ vault_ha_client.vault_root_ca_cert_file }}"
      VAULT_CLIENT_CERT: "{{ vault_ha_client.vault_client_cert_file }}"
      VAULT_CLIENT_KEY: "{{ vault_ha_client.vault_client_key_file }}"
  register: __minio_details

- name: Mini0 | Set config facts
  ansible.builtin.set_fact:
      cs_minio_minio_port: "{{ __minio_details.secret.port }}"
      cs_minio_minio_console_port: "{{ __minio_details.secret.console_port }}"
      cs_minio_minio_region: "{{ __minio_details.secret.region }}"

- name: Minio | Assert | Set cs_minio_minio_kes_cluster_name and cs_minio_minio_kes_cluster_node_name
  ansible.builtin.set_fact:
      cs_minio_minio_kes_cluster_name: "{{ cs_minio_minio_kes_cluster_name | d(cs_minio_minio_cluster_name)
          | mandatory }}"
      cs_minio_minio_kes_cluster_node_name: "{{ cs_minio_minio_kes_cluster_node_name | d(inventory_hostname)
          | mandatory }}"

- name: Minio | Get KES Admin Key Id from Vault
  become: false
  delegate_facts: true
  delegate_to: localhost
  community.hashi_vault.vault_kv2_get:
      url: "https://{{ vault_ha_client.vault_ha_hostname }}:{{ vault_ha_client.vault_ha_port }}"
      engine_mount_point: "managed-secrets"
      path: "minio-kes/clusters/{{ cs_minio_kes_cluster_name }}/servers/{{ cs_minio_minio_kes_cluster_node_name }}\
          /config"
      token: "{{ vault_ha_client.token }}"
      validate_certs: true
  register: __minio_server_kes_secret_dict
  environment:
      VAULT_CACERT: "{{ vault_ha_client.vault_root_ca_cert_file }}"
      VAULT_CLIENT_CERT: "{{ vault_ha_client.vault_client_cert_file }}"
      VAULT_CLIENT_KEY: "{{ vault_ha_client.vault_client_key_file }}"

- name: Minio | Set cs_minio_minio_kes_endpoint
  ansible.builtin.set_fact:
      cs_minio_minio_kes_endpoint: "https://{{ __minio_server_kes_secret_dict.secret.fqdn }}:\
          {{ __minio_server_kes_secret_dict.secret.port }}"

- name: Minio | Install | Create group
  ansible.builtin.group:
      name: "{{ cs_minio_minio_group_name }}"
      state: present
      system: true
  register: minio_server_tmp_group_creation

- name: Minio | Install | Create User
  ansible.builtin.user:
      name: "{{ cs_minio_minio_user_name }}"
      group: "{{ cs_minio_minio_group_name }}"
      state: present
      create_home: false
      system: true
      shell: /bin/false
  register: minio_server_tmp_user_creation

- name: Minio | Install | Download binary
  ansible.builtin.get_url:
      dest: "/usr/local/bin/minio"
      mode: "0755"
      owner: root
      group: root
      checksum: "sha256:{{ cs_minio_minio_bin_info_map[ansible_architecture]['sha256sum'][cs_minio_minio_version] }}"
      url: "https://dl.min.io/server/minio/release/linux-\
          {{ cs_minio_minio_bin_info_map[ansible_architecture]['cs_minio_minio_arch'] }}/archive/minio.\
          {{ cs_minio_minio_version }}"

- name: Minio | Install | Create Directories
  ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      owner: "{{ cs_minio_minio_user_name }}"
      group: "{{ cs_minio_minio_group_name }}"
      mode: "0777"
  loop:
      - "{{ cs_minio_minio_certs_dir }}"
      - "{{ cs_minio_minio_certs_dir }}/CAs"
      - "{{ cs_minio_minio_data_dir }}"
      - "{{ cs_minio_minio_kes_cert_dir }}"

- name: Minio | Install | Fix Permissions of data directory
  ansible.builtin.shell:
      cmd: |+
          chown -R {{ cs_minio_minio_user_name }}:{{ cs_minio_minio_group_name }} {{ item }};
          find {{ item }} -type d -exec chmod 0777 {} \;
          find {{ item }} -type f -exec chmod 0777 {} \;
  changed_when: true
  with_items:
      - "{{ cs_minio_minio_data_dir }}"
      - "{{ cs_minio_minio_certs_dir }}"
      - "{{ cs_minio_minio_kes_cert_dir }}"

- name: Minio | Install | Get Minio Server Certificates from Vault
  become: false
  delegate_facts: true
  delegate_to: localhost
  community.hashi_vault.vault_write:
      timeout: 60
      url: "https://{{ vault_ha_client.vault_ha_hostname }}:{{ vault_ha_client.vault_ha_port }}"
      path: pki/issue/server_certificate
      token: "{{ vault_ha_client.token }}"
      validate_certs: true
      data:
          common_name: "{{ inventory_hostname }}"
          alt_names: "{{ ansible_fqdn }},{{ ansible_hostname }}"
          ip_sans: "{{ ansible_all_ipv4_addresses | join(',') }}"
  register: minio_server_tmp_certificate
  environment:
      VAULT_CACERT: "{{ vault_ha_client.vault_root_ca_cert_file }}"
      VAULT_CLIENT_CERT: "{{ vault_ha_client.vault_client_cert_file }}"
      VAULT_CLIENT_KEY: "{{ vault_ha_client.vault_client_key_file }}"

- name: Minio | Install | Write Server Certificates
  ansible.builtin.copy:
      content: "{{ item.content }}"
      dest: "{{ item.dest }}"
      owner: "{{ cs_minio_minio_user_name }}"
      group: "{{ cs_minio_minio_group_name }}"
      mode: "0644"
  loop:
      - content: "{{ minio_server_tmp_certificate.data.data.certificate }}\n\
            {{ minio_server_tmp_certificate.data.data.ca_chain | join('\n') }}\n"
        dest: "{{ cs_minio_minio_cert_file }}"
      - content: "{{ minio_server_tmp_certificate.data.data.private_key }}\n"
        dest: "{{ cs_minio_minio_private_key }}"
      - content: "{{ minio_server_tmp_certificate.data.data.ca_chain | join('\n') }}\n"
        dest: "{{ cs_minio_minio_ca_file }}"

- name: Minio | Install | Write KES Client Admin Certificates
  ansible.builtin.copy:
      content: "{{ item.content }}"
      dest: "{{ item.dest }}"
      owner: "{{ cs_minio_minio_user_name }}"
      group: "{{ cs_minio_minio_group_name }}"
      mode: "0777"
  loop:
      - content: "{{ __minio_server_kes_secret_dict.secret.admin_cert }}\n"
        dest: "{{ cs_minio_minio_kes_admin_cert }}"
      - content: "{{ __minio_server_kes_secret_dict.secret.admin_key }}\n"
        dest: "{{ cs_minio_minio_kes_admin_key }}"
      - content: "{{ __minio_server_kes_secret_dict.secret.admin_ca }}\n"
        dest: "{{ cs_minio_minio_kes_ca_cert }}"

- name: Minio | Install | Create User and Password
  ansible.builtin.set_fact:
      minio_server_root_password: "{{ lookup('ansible.builtin.password', '/dev/null', length=40,
          chars=['ascii_letters', 'digits']) }}"
      minio_server_root_user: "{{ lookup('community.general.random_string', special=false, length=12) }}"

- name: Minio | Install | Write the Password to Vault
  become: false
  delegate_facts: true
  delegate_to: localhost
  community.hashi_vault.vault_kv2_write:
      url: "https://{{ vault_ha_client.vault_ha_hostname }}:{{ vault_ha_client.vault_ha_port }}"
      path: "minio/clusters/{{ cs_minio_minio_cluster_name }}/servers/{{ inventory_hostname }}/config"
      token: "{{ vault_ha_client.token }}"
      validate_certs: true
      engine_mount_point: "managed-secrets"
      data:
          root_user: "{{ minio_server_root_user }}"
          root_password: "{{ minio_server_root_password }}"
          ipv4s: "{{ ansible_all_ipv4_addresses }}"
          hostname: "{{ ansible_hostname }}"
          fqdn: "{{ ansible_fqdn }}"
          server_port: "{{ cs_minio_minio_port }}"
          console_port: "{{ cs_minio_minio_console_port }}"
          server_version: "{{ cs_minio_minio_version }}"
          kes:
              cluster_name: "{{ cs_minio_minio_kes_cluster_name }}"
              cluster_node_name: "{{ cs_minio_minio_kes_cluster_node_name }}"
  environment:
      VAULT_CACERT: "{{ vault_ha_client.vault_root_ca_cert_file }}"
      VAULT_CLIENT_CERT: "{{ vault_ha_client.vault_client_cert_file }}"
      VAULT_CLIENT_KEY: "{{ vault_ha_client.vault_client_key_file }}"

- name: Minio | Install | Create Env File
  ansible.builtin.copy:
      content: |+
          MINIO_KMS_KES_ENDPOINT={{ cs_minio_minio_kes_endpoint }}
          MINIO_KMS_KES_KEY_FILE={{ cs_minio_minio_kes_admin_key }}
          MINIO_KMS_KES_CERT_FILE={{ cs_minio_minio_kes_admin_cert }}
          MINIO_KMS_KES_CAPATH={{ cs_minio_minio_kes_ca_cert }}
          MINIO_KMS_KES_KEY_NAME=default
          MINIO_ROOT_USER={{ minio_server_root_user }}
          MINIO_ROOT_PASSWORD={{ minio_server_root_password }}
          MINIO_REGION=us-east-1
          MINIO_VOLUMES={{ cs_minio_minio_data_dir }}
          MINIO_OPTS="--address ':{{ cs_minio_minio_port }}' --console-address ':{{
            cs_minio_minio_console_port }}' --certs-dir {{ cs_minio_minio_certs_dir }}"
      dest: "{{ cs_minio_minio_env_file }}"
      owner: "{{ cs_minio_minio_user_name }}"
      group: "{{ cs_minio_minio_group_name }}"
      mode: "0777"

- name: Minio | Install | Enable UFW
  community.general.ufw:
      rule: allow
      port: "{{ item.port }}"
      proto: tcp
      state: enabled
      comment: "Allow Mini0 {{ item.comment }} port, Managed by Ansible home-lab playbook."
  loop:
      - port: "{{ cs_minio_minio_port }}"
        comment: "S3"
      - port: "{{ cs_minio_minio_console_port }}"
        comment: "Console"

- name: Minio | Install | Create Systemd Service
  ansible.builtin.template:
      src: "templates/minio/{{ cs_minio_minio_systemd_service }}.j2"
      dest: "/etc/systemd/system/{{ cs_minio_minio_systemd_service }}"
      owner: root
      group: root
      mode: "0644"

- name: Minio | Install | Start Systemd Service
  ansible.builtin.systemd_service:
      name: "{{ cs_minio_minio_systemd_service }}"
      state: restarted
      daemon_reload: true
      daemon_reexec: true
      enabled: true
      force: true

- name: Minio | Install | Wait for Minio to start
  ansible.builtin.uri:
      url: "https://{{ ansible_all_ipv4_addresses[0] }}:{{ cs_minio_minio_port }}/minio/health/live"
      status_code: 200
      timeout: 3
      method: GET
  register: minio_server_health_check
  until: minio_server_health_check.status == 200
  retries: 10
  delay: 1
