---
- name: Nextcloud | Cache | Redis | Create Client Certificate Directories
  ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: "0755"
      owner: "{{ cs_nc_run_user }}"
      group: "{{ cs_nc_run_group }}"
  with_items:
      - "{{ cs_nc_redis_cert_dir }}"
      - "{{ cs_nc_redis_privkey_file | dirname }}"
      - "{{ cs_nc_redis_cert_file | dirname }}"
      - "{{ cs_nc_redis_ca_file | dirname }}"

- name: Nextcloud | Cache | Redis | Get server certificates from Vault
  become: false
  delegate_facts: true
  delegate_to: localhost
  community.hashi_vault.vault_kv2_get:
      url: "https://{{ vault_ha_client.vault_ha_hostname }}:{{ vault_ha_client.vault_ha_port }}"
      engine_mount_point: "managed-secrets"
      path: "redis/clusters/{{ cs_nc_redis_cluster_name }}/servers/{{ cs_nc_redis_cluster_node }}/config"
      token: "{{ vault_ha_client.token }}"
      validate_certs: true
  register: __nextcloud_redis_details
  environment:
      VAULT_CACERT: "{{ vault_ha_client.vault_root_ca_cert_file }}"
      VAULT_CLIENT_CERT: "{{ vault_ha_client.vault_client_cert_file }}"
      VAULT_CLIENT_KEY: "{{ vault_ha_client.vault_client_key_file }}"

- name: Nextcloud | Cache | Redis | Set db fact
  ansible.builtin.set_fact:
      cs_nc_redis_port: "{{ __nextcloud_redis_details.secret.tls_port }}"
      cs_nc_redis_password: "{{ __nextcloud_redis_details.secret.admin_password }}"
      cs_nc_redis_host: "{{ __nextcloud_redis_details.secret.fqdn }}"

- name: Nextcloud | Cache | Redis | Get Client Certificates from Vault
  become: false
  delegate_facts: true
  delegate_to: localhost
  community.hashi_vault.vault_write:
      url: "https://{{ vault_ha_client.vault_ha_hostname }}:{{ vault_ha_client.vault_ha_port }}"
      path: pki/issue/client_certificate
      token: "{{ vault_ha_client.token }}"
      validate_certs: true
      data:
          common_name: "{{ cs_nc_redis_host }}"
          alt_names: "{{ cs_nc_redis_host }}"
  register: __redis_client_cert
  environment:
      VAULT_CACERT: "{{ vault_ha_client.vault_root_ca_cert_file }}"
      VAULT_CLIENT_CERT: "{{ vault_ha_client.vault_client_cert_file }}"
      VAULT_CLIENT_KEY: "{{ vault_ha_client.vault_client_key_file }}"

- name: Nextcloud | Cache | Redis | Write Client Certificates to disk
  ansible.builtin.copy:
      content: "{{ item.content }}"
      dest: "{{ item.dest }}"
      owner: "{{ cs_nc_run_user }}"
      group: "{{ cs_nc_run_group }}"
      mode: "0600"
  loop:
      - content: "{{ __redis_client_cert.data.data.certificate }}\n\
            {{ __redis_client_cert.data.data.ca_chain | join('\n') }}"
        dest: "{{ cs_nc_redis_cert_file }}"
      - content: "{{ __redis_client_cert.data.data.private_key }}"
        dest: "{{ cs_nc_redis_privkey_file }}"
      - content: "{{ __redis_client_cert.data.data.ca_chain | join('\n') }}"
        dest: "{{ cs_nc_redis_ca_file }}"

- name: Nextcloud | Cache | Write temp config
  ansible.builtin.copy:
      content: "{{ cs_nc_redis_cache_config | to_json }}"
      dest: "/tmp/nc_redis_cache_config.json"
      mode: "0644"
  vars:
      cs_nc_redis_cache_config:
          system:
              redis:
                  host: "{{ cs_nc_redis_host }}"
                  port: "{{ cs_nc_redis_port }}"
                  timeout: "{{ cs_nc_redis_timeout }}"
                  password: "{{ cs_nc_redis_password }}"
                  ssl_context:
                      local_cert: "{{ cs_nc_redis_cert_file }}"
                      local_pk: "{{ cs_nc_redis_privkey_file }}"
                      cafile: "{{ cs_nc_redis_ca_file }}"
                      verify_peer_name: false
              memcache.local: "\\OC\\Memcache\\APCu"
              memcache.distributed: "\\OC\\Memcache\\Redis"
              memcache.locking: "\\OC\\Memcache\\Redis"

- name: Nextcloud | Cache | Set nextcloud config
  become: true
  become_user: "{{ cs_nc_run_user }}"
  ansible.builtin.command:
      cmd: "php occ config:import /tmp/nc_redis_cache_config.json"
      chdir: "{{ cs_nc_web_dir }}"
  changed_when: true

- name: Nextcloud | Cache | Remove temp config
  ansible.builtin.file:
      path: "/tmp/nc_redis_cache_config.json"
      state: absent
