---
- name: Nextcloud | Cache | Redis | Create Client Certificate Directories
  ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: "0755"
      owner: "{{ cs_nc_run_user }}"
      group: "{{ cs_nc_run_group }}"
  with_items:
      - "{{ cs_nc_redis_cert_dir }}"
      - "{{ cs_nc_redis_privkey_file | dirname }}"
      - "{{ cs_nc_redis_cert_file | dirname }}"
      - "{{ cs_nc_redis_ca_file | dirname }}"

- name: Nextcloud | Cache | Redis | Set db fact
  ansible.builtin.set_fact:
      cs_nc_redis_port: "{{ __nextcloud_redis_details.tls_port }}"
      cs_nc_redis_password: "{{ __nextcloud_redis_details.admin_password }}"
      cs_nc_redis_host: "{{ __nextcloud_redis_details.host }}"
  vars:
      __nextcloud_redis_details: "{{ lookup('lab_secrets', 'managed-secrets/redis/clusters/'
          + cs_nc_redis_cluster_name + '/servers/' + cs_nc_redis_cluster_node + '/config') }}"

- name: Nextcloud | Cache | Redis | Write client private key
  community.crypto.openssl_privatekey:
      path: "{{ cs_nc_redis_privkey_file }}"
      type: RSA
      size: 4096
      mode: "0600"
      owner: "{{ cs_nc_run_user }}"
      group: "{{ cs_nc_run_group }}"

- name: Nextcloud | Cache | Redis | Write client CSR
  community.crypto.openssl_csr:
      path: "{{ cs_nc_redis_privkey_file }}.csr"
      privatekey_path: "{{ cs_nc_redis_privkey_file }}"
      common_name: "{{ cs_nc_redis_host }}"
      basic_constraints: CA:FALSE
      basic_constraints_critical: true
      key_usage:
          - digitalSignature
          - keyEncipherment
      extended_key_usage:
          - clientAuth
      mode: "0600"
      owner: "{{ cs_nc_run_user }}"
      group: "{{ cs_nc_run_group }}"

- name: Nextcloud | Cache | Redis | Write client Certificate
  community.crypto.x509_certificate:
      path: "{{ cs_nc_redis_cert_file }}"
      csr_path: "{{ cs_nc_redis_privkey_file }}.csr"
      ownca_content: "{{ root_ca_cert_pem }}"
      ownca_privatekey_content: "{{ root_ca_key_pem }}"
      ownca_privatekey_passphrase: "{{ root_ca_key_password }}"
      provider: ownca
      mode: "0600"
      owner: "{{ cs_nc_run_user }}"
      group: "{{ cs_nc_run_group }}"

- name: Nextcloud | Cache | Redis | Write client chain certificate
  ansible.builtin.copy:
      content: "{{ root_ca_cert_pem }}"
      dest: "{{ cs_nc_redis_ca_file }}"
      mode: "0600"
      owner: "{{ cs_nc_run_user }}"
      group: "{{ cs_nc_run_group }}"
      remote_src: false

- name: Nextcloud | Cache | Write temp config
  ansible.builtin.copy:
      content: "{{ cs_nc_redis_cache_config | to_json }}"
      dest: "/tmp/nc_redis_cache_config.json"
      mode: "0644"
  vars:
      cs_nc_redis_cache_config:
          system:
              redis:
                  host: "{{ cs_nc_redis_host }}"
                  port: "{{ cs_nc_redis_port }}"
                  timeout: "{{ cs_nc_redis_timeout }}"
                  password: "{{ cs_nc_redis_password }}"
                  ssl_context:
                      local_cert: "{{ cs_nc_redis_cert_file }}"
                      local_pk: "{{ cs_nc_redis_privkey_file }}"
                      cafile: "{{ cs_nc_redis_ca_file }}"
                      verify_peer_name: false
              memcache.local: "\\OC\\Memcache\\APCu"
              memcache.distributed: "\\OC\\Memcache\\Redis"
              memcache.locking: "\\OC\\Memcache\\Redis"

- name: Nextcloud | Cache | Set nextcloud config
  become: true
  become_user: "{{ cs_nc_run_user }}"
  ansible.builtin.command:
      cmd: "php occ config:import /tmp/nc_redis_cache_config.json"
      chdir: "{{ cs_nc_web_dir }}"
  changed_when: true

- name: Nextcloud | Cache | Remove temp config
  ansible.builtin.file:
      path: "/tmp/nc_redis_cache_config.json"
      state: absent
