---
- name: Nextcloud | Data Dump | Include common crypt mount
  ansible.builtin.include_tasks:
      file: tasks/common/crypt_mount.yml
  vars:
      cs_crypt_mount_vault_id: "{{ cs_nextcloud_backup_drive_external_disk_id }}"

- name: Nextcloud | Data Dump | Directory
  ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: "0755"
      owner: "{{ cs_nc_run_user }}"
      group: "{{ cs_nc_run_group }}"
  with_items:
      - "{{ cs_nc_external_drive_mount_data_dump_path }}"
      - "{{ cs_nc_external_drive_mount_data_dump_path }}/current"

- name: Nextcloud | Data Dump | Install rsync
  ansible.builtin.apt:
      name:
          - rsync
          - zstd
      state: present

- name: Nextcloud | Data Dump | Get DB Details
  become: false
  delegate_facts: true
  delegate_to: localhost
  community.hashi_vault.vault_kv2_get:
      url: "https://{{ vault_ha_client.vault_ha_hostname }}:{{ vault_ha_client.vault_ha_port }}"
      engine_mount_point: "managed-secrets"
      path: "postgresql/clusters/{{ cs_nc_db_cluster_name }}/servers/{{ cs_nc_db_cluster_node }}/db/{{
          cs_nc_db_database }}"
      token: "{{ vault_ha_client.token }}"
      validate_certs: true
  register: __nextcloud_db_details
  environment:
      VAULT_CACERT: "{{ vault_ha_client.vault_root_ca_cert_file }}"
      VAULT_CLIENT_CERT: "{{ vault_ha_client.vault_client_cert_file }}"
      VAULT_CLIENT_KEY: "{{ vault_ha_client.vault_client_key_file }}"

- name: Nextcloud | Data Dump | Set db fact
  ansible.builtin.set_fact:
      cs_nc_db_user: "{{ __nextcloud_db_details.secret.user }}"
      cs_nc_db_password: "{{ __nextcloud_db_details.secret.password }}"
      cs_nc_db_host: "{{ __nextcloud_db_details.secret.private_ip }}"
      cs_nc_db_port: "{{ __nextcloud_db_details.secret.server_port }}"
      cs_nc_db_version: "{{ __nextcloud_db_details.secret.server_version }}"

- name: Nextcloud | Data Dump | Create Environment File
  ansible.builtin.template:
      mode: "0755"
      dest: "{{ cs_nc_root_dir }}/.create_dump.env"
      src: "templates/nc/dump-env.j2"

- name: Nextcloud | Data Dump | Create Script
  ansible.builtin.copy:
      mode: "0755"
      dest: "{{ cs_nc_root_dir }}/create_dump.sh"
      src: files/nc/create_dump.sh
      remote_src: false

- name: Nextcloud | Data Dump | Create systemd service
  ansible.builtin.template:
      mode: "0644"
      dest: "/etc/systemd/system/nextcloud-data-dump.service"
      src: "templates/nc/nextcloud-data-dump.service.j2"

- name: Nextcloud | Data Dump | Create systemd timer
  ansible.builtin.copy:
      mode: "0644"
      dest: "/etc/systemd/system/nextcloud-data-dump.timer"
      src: files/nc/nextcloud-data-dump.timer
      remote_src: false

- name: Nextcloud | Data Dump | Make sure cron systemd service is enabled
  ansible.builtin.systemd_service:
      name: nextcloud-data-dump.timer
      enabled: true
      state: started
      daemon_reload: true
