---
- name: Nextcloud | Full Text Search | List all apps
  become: true
  become_user: "{{ cs_nc_run_user }}"
  ansible.builtin.command:
      cmd: "php occ app:list --output=json"
      chdir: "{{ cs_nc_web_dir }}"
  changed_when: false
  register: cs_nc_app_list_fulltextsearch

- name: Nextcloud | Full Text Search | Install apps
  become: true
  become_user: "{{ cs_nc_run_user }}"
  ansible.builtin.command:
      cmd: "php occ app:install {{ item }}"
      chdir: "{{ cs_nc_web_dir }}"
  changed_when: true
  with_items:
      - "fulltextsearch"
      - "files_fulltextsearch"
      - "fulltextsearch_elasticsearch"
  when: >
      not
      (
        item in cs_nc_app_list_fulltextsearch.stdout | from_json | community.general.json_query('enabled')
      or
        item in cs_nc_app_list_fulltextsearch.stdout | from_json | community.general.json_query('disabled')
      )

- name: Nextcloud | Full Text Search | create {{ cs_nc_fts_elasticsearch_systemd }}
  ansible.builtin.template:
      dest: /etc/systemd/system/{{ cs_nc_fts_elasticsearch_systemd }}.service
      src: templates/nc/{{ cs_nc_fts_elasticsearch_systemd }}.service.j2
      mode: "0644"

- name: Nextcloud | Full Text Search | Set db fact
  ansible.builtin.set_fact:
      cs_nc_fts_elasticsearch_servlet_port: "{{ __nextcloud_fts_details.servlet_port }}"
      cs_nc_fts_elasticsearch_password: "{{ __nextcloud_fts_details.root_password }}"
      cs_nc_fts_elasticsearch_host: "{{ __nextcloud_fts_details.fqdn }}"
  vars:
      __nextcloud_fts_details: "{{ lookup('home_lab_secrets', 'managed-secrets/elasticsearch/clusters/' +
          cs_nc_elasticsearch_cluster_name + '/servers/' + cs_nc_elasticsearch_cluster_node + '/config') }}"

- name: Nextcloud | Full Text Search | Write Apps Config
  ansible.builtin.copy:
      content: "{{ cs_nc_app_config_fulltextsearch | to_nice_json }}"
      dest: "/tmp/nc-apps-fulltextsearch-config.json"
      mode: "0644"
  vars:
      cs_nc_app_config_fulltextsearch:
          apps:
              fulltextsearch:
                  app_navigation: "1"
                  enabled: "yes"
                  search_platform: "OCA\\FullTextSearch_Elasticsearch\\Platform\\ElasticSearchPlatform"
                  types: ""
              fulltextsearch_elasticsearch:
                  enabled: "yes"
                  elastic_host: "http://elastic:{{ cs_nc_fts_elasticsearch_password }}@{{
                      cs_nc_fts_elasticsearch_host }}:{{ cs_nc_fts_elasticsearch_servlet_port }}"
                  elastic_index: "{{ cs_nc_fts_elasticsearch_index_name }}"
                  elastic_type: "file"
                  analyzer_tokenizer: "standard"
                  types: ""
              files_fulltextsearch:
                  enabled: "yes"
                  types: "filesystem"
                  files_local: "1"
                  files_size: "20"
                  files_pdf: "1"
                  files_office: "1"
                  files_image: "0"
                  files_audio: "0"
                  files_group_folders: "1"
                  files_external: "1"

- name: Nextcloud | Full Text Search | Import Apps Config
  become: true
  become_user: "{{ cs_nc_run_user }}"
  ansible.builtin.command:
      cmd: "php occ config:import /tmp/nc-apps-fulltextsearch-config.json"
      chdir: "{{ cs_nc_web_dir }}"
  changed_when: true

- name: Nextcloud | Full Text Search | Stop {{ cs_nc_fts_elasticsearch_systemd }}
  ansible.builtin.systemd_service:
      name: "{{ cs_nc_fts_elasticsearch_systemd }}.service"
      enabled: false
      state: stopped
      daemon_reload: true

- name: Nextcloud | Full Text Search | Stop fulltextsearch
  become: true
  become_user: "{{ cs_nc_run_user }}"
  ansible.builtin.command:
      cmd: "php occ fulltextsearch:stop"
      chdir: "{{ cs_nc_web_dir }}"
  changed_when: true

- name: Nextcloud | Full Text Search | Start {{ cs_nc_fts_elasticsearch_systemd }}
  ansible.builtin.systemd_service:
      name: "{{ cs_nc_fts_elasticsearch_systemd }}.service"
      enabled: true
      state: started
      daemon_reload: true
