---
cs_nc_db_cluster_name: blr-home
cs_nc_db_cluster_node: rb4-m1

cs_nc_redis_cluster_name: blr-home
cs_nc_redis_cluster_node: rb4-m2

cs_nc_elasticsearch_cluster_name: blr-home
cs_nc_elasticsearch_cluster_node: rb4-m2

cs_nextcloud_external_disk_id: "p2-2tb-rb4-m2"

cs_nextcloud_backup_drive_external_disk_id: "p2-2tb-rb4-m2"
cs_nc_external_drive_mount_data_dump_path: "/mnt/{{ cs_nextcloud_backup_drive_external_disk_id }}/nextcloud-data-dump"
