---
name: Black

"on":
    workflow_dispatch:
    pull_request:
        paths:
            - "**.py"
            - ".github/workflows/black.yml"
            - "poetry.lock"
            - "pyproject.toml"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    black:
        timeout-minutes: 60
        cancel-timeout-minutes: 60
        runs-on: ubuntu-24.04
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.11", "3.12", "3.13"]
        name: black
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: Install poetry 2.0.1
              run: pipx install poetry==2.0.1

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5.3.0
              with:
                  python-version: "${{ matrix.python-version }}"
                  cache: "poetry"
                  cache-dependency-path: poetry.lock

            - name: Install dependencies
              run: poetry install --with dev

            - name: Analyzing the code with black
              run: poetry run black --check $(git ls-files '*.py')
