---
name: Yamllint

"on":
    push:
        paths:
            - "**.yaml"
            - "**.yml"
            - ".github/workflows/yamllint.yml"
            - ".yamllint"
            - "poetry.lock"
            - "pyproject.toml"
    workflow_dispatch:
    pull_request:
        paths:
            - "**.yaml"
            - "**.yml"
            - ".github/workflows/yamllint.yml"
            - ".yamllint"
            - "poetry.lock"
            - "pyproject.toml"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    yamllint:
        timeout-minutes: 60
        cancel-timeout-minutes: 60
        runs-on: ubuntu-24.04
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.11", "3.12", "3.13"]
        name: yamllint
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: Install poetry 1.8.5
              run: pipx install poetry==2.0.0

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5.3.0
              with:
                  python-version: "${{ matrix.python-version }}"
                  cache: "poetry"
                  cache-dependency-path: poetry.lock

            - name: Install dependencies
              run: poetry install --with dev

            - name: Analysing the code with yamllint
              run: poetry run yamllint .
